name: advanced-fp-assignment-two
version: 0.1.0.0
github: "shadowmanu/academics"
license: MIT
author: "Manuel Pacheco"
maintainer: "manuelalejandropm@gmail.com"
copyright: "2019 Manuel Pacheco"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/ShadowManu/academics/blob/master/programming-languages/haskinator/README.md>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  bonus:
    main: Bonus.hs
    source-dirs: bonus

  # logo:
  #   main: Logo.hs
  #   source-dirs: logo
  #   dependencies:
  #     - containers
  #     - HGL
  #     - mtl
  #     - transformers

  pizza:
    main: Pizza.hs
    source-dirs: pizza
